spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://39.108.52.95:3306/rna_transcription?useUnicode=true&characterEncoding=UTF-8&useSSL=false
     username: ldchao
     password: 123456