spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://114.115.136.191:3306/rna_transcription?useUnicode=true&characterEncoding=UTF-8&useSSL=false
     username: yuanquan
     password: 123456